# Generated by Django 5.0 on 2023-12-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=80)),
                ('user_email', models.CharField(max_length=180)),
                ('user_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
