# Generated by Django 5.0 on 2023-12-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_users_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_messages',
            name='reply',
        ),
    ]
