# Generated by Django 5.0 on 2023-12-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_users_messages_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_messages',
            old_name='message',
            new_name='conversation_history',
        ),
    ]
