# Generated by Django 5.0 on 2023-12-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_users_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_messages',
            old_name='conversation_history',
            new_name='ai_response',
        ),
        migrations.AddField(
            model_name='users_messages',
            name='message_text',
            field=models.TextField(default='Default message text'),
        ),
        migrations.AlterField(
            model_name='users_messages',
            name='user_id',
            field=models.CharField(max_length=1000),
        ),
    ]
