# Generated by Django 5.0 on 2023-12-28 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_rename_conversation_history_users_messages_ai_response_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users_messages',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='users_messages',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
